spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://100.64.0.8:10000/common-oms-dev
    username: common-oms-dev
    password: AhJckjVnWgB0wb1
qiniuyun:
  access-key: TY6utcq7Koaf9jcsfn7riNg5VKQbvowoUZXTyvZv
  secret-key: 33tE5JHA9b6ytwABXnnloVrGiUhoEHktVa6Ye-NB
  bucket: eggcampus-test
  domain-of-bucket: test.img.eggcampus.com
  image-size-limit: 2MB
  oss-callback-domain: https://dev.oms-server.eggcampus.com
seata:
  application-id: common-oms
  tx-service-group: default
  service:
    vgroup-mapping:
      default: default
    grouplist:
      default: 100.64.0.8:10002